### ISSUE TITLE
Project abandoned?

### ISSUE THREAD

**Issue by ShaneD53** [shadeMe/Creation-Kit-Extender#2]
Has this been abandoned? Is there any chance of you coming back to do this for the special edition CK? 

Sorry for abusing the issues system I've been trying to find other ways to contact you about this because your work is something beyond amazing and the Skyrim modding community needs you.

**Comment by shadeMe** [comment]
I'm afraid so - I don't have a lot of time to mod these days. The code in the repo isn't of much use to the SSE CK as it is a 64-bit application. The SKSE64 codebase would be a better starting point for the CKE, if someone else picks up the torch.

**Comment by ShaneD53** [comment]
Ah, too bad. Are you by any chance open for contract work? If so, shoot me an email at leroy.dalton1@gmail.com
